### ISSUE TITLE
Custom line-size warning

### ISSUE THREAD

**Issue by bryanllewis** [dzwillia/vue-simple-spinner#19]
The component works fine with all defaults, and I can provide any custom props that are strings (such as "line-bg-color").  However, if I try to provide a custom line-size, it throws a console warning.

`<spinner line-size="5" line-bg-color="#fff"></spinner>`

Produces this warning:

`[Vue warn]: Invalid prop: type check failed for prop "lineSize". Expected Number with value 5, got String with value "5".`

**It works**, but the warning is not ideal.

**Comment by dzwillia** [comment]
Hi there!

Thanks for your interest in VueSimpleSpinner. The `line-size` prop needs to be a number since it is used for a number of internal calculations. If you add a `:` in front of the prop, you should be good to go -- this tells Vue.js to interpret the value as a number.

```<spinner :line-size="5" line-bg-color="#fff"></spinner>```

You can check the documentation for a [list of available options](https://github.com/dzwillia/vue-simple-spinner#options).

Hope that helps!

**Comment by bryanllewis** [comment]
Thanks Dave.  I am fairly new to Vue and I forgot about that.  But I was following your "live" JSFiddle examples and the colon is missing from those.  May want to update.
